### ISSUE TITLE
Github release in release format

### ISSUE THREAD

**Issue by enesaltinkaya** [disks86/VK9#53] opened 2018-07-22 15:59 UTC
Can you release compiled version in release mode please?

Trying to run dll's in debug mod requires ****d.dll (msvcp140d.dll)

Can be problematic.

**Comment by disks86** [comment] 2018-07-27 01:05
This is a duplicate of #52 and #44 . I'll make sure to include release builds in the next release.

**Comment by disks86** [comment] 2018-08-09 01:17
The most recent build contains a release build.

**Closed by disks86** 2018-08-09 01:17 UTC
Labels: duplicate
