### ISSUE TITLE
Possible regression in 0.26.0 - loading library failed

### ISSUE THREAD

**Issue by aladar42** [disks86/VK9#52] opened 2018-06-27 20:42 UTC
Hey, I'm trying VK9 and I get this every time I try to run BlazBlue Cross Tag Battle:

>$ wine BBTAG
0009:err:module:import_dll Loading library d3d9.dll (which is needed by L"Z:\\run\\media\\aladar\\fad599b8-eb10-4814-95bd-fa0e60942ce7\\home\\aladar\\BlazBlue - Cross Tag Battle\\BBTAG.exe") failed (error c000007b).
0009:err:module:attach_dlls Importing dlls for L"Z:\\run\\media\\aladar\\fad599b8-eb10-4814-95bd-fa0e60942ce7\\home\\aladar\\BlazBlue - Cross Tag Battle\\BBTAG.exe" failed, status c0000135

However, downgrading the dll to 0.25.0 does launch the game, even though it immediately crashes with an error:

>$ wine BBTAG
0009:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x32e968 1 C) semi-stub
0009:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x401123, 0x97a4b0, 0x97a4c8) stub.
0009:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x945830, 43) stub
002d:fixme:ver:GetCurrentPackageId (0x244fe9c (nil)): stub
[2018-06-27 22:38:09.608191] [0x00000009] [warning] Direct3DCreate9Ex is not implemented!

Am I doing soemthing wrong or is this a bug?

**Comment by MrChebik** [comment] 2018-06-27 21:13
@aladar42 Sorry, but it's a joke?
You try to run game of 2018 year with **VK9**?

Now this project is at a very early stage of development. And can run simple projects / demos.
Сonsidering that there are few people working on the project, and everything creates from scratch (if I understand correctly).

For example, I can't to run **Asterix XXL** with **VK9**.

**Comment by doitsujin** [comment] 2018-06-27 21:37
The interesting part is this:
> 0009:err:module:import_dll Loading library d3d9.dll

This means that
- either wine genuinely can't find your `d3d9.dll`
- your `d3d9.dll` has the wrong architecture
- you are using the debug DLLs, which do not work on wine (use the release builds instead).
- it fails to load some dependency.

You could try to get some more verbose output with `WINEDEBUG=module`.

**Comment by qwertychouskie** [comment] 2018-06-27 22:03
Probably a dupe of https://github.com/disks86/VK9/issues/44

**Comment by aladar42** [comment] 2018-06-27 22:10
Could be. I tried to build the dlls myself but for some reason the compiler is throwing errors about missing boost dependency, even though I do have boost installed and followed the project Wiki to get the additional libs compiled. No idea how to go about that...

**Comment by disks86** [comment] 2018-08-09 01:17
The most recent build contains a release build.

**Closed by disks86** 2018-08-09 01:17 UTC
